[package]
name = "mandelbrot"
version = "0.1.0"
publish = false
authors = ["Earvin Kayonga <earvin@earvinkayonga.com>"]
description = "Generating fractal image"

[dependencies]
raster = "^0.2"
failure = "0.1"